version: "3"


services:

  team_quest_bot:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    environment:
      - PYTHONPATH=.
      - TZ=${TZ:-Europe/Minsk}
      - LOGLEVEL=${LOGLEVEL}
      - GIT_VERSION=${GIT_VERSION}
      - BOT_API_KEY=${BOT_API_KEY}
