version: "3"


services:

  team_quest_bot:
    init: true
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./quests:/srv/team_quest_bot/quests
    environment:
      - PYTHONPATH=.
      - TZ=${TZ:-Europe/Minsk}
      - LOGLEVEL=${LOGLEVEL}
      - GIT_VERSION=${GIT_VERSION}
      - BOT_API_KEY=${BOT_API_KEY}
